### ISSUE TITLE
✨ CI: Build x86

### ISSUE THREAD

**Issue by AddressXception** [microsoft/electionguard-core2#103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Suggestion

CI does not currently build x86 msvc. This ticket is to add support for cross-compiling x86 on windows from an x64 host

### Possible Implementation

Add this to the PR workflow

```yaml
- name: windows-2022-msvc-latest-x86
  os: windows-2022
  processor: x86
  compiler: msvc
  version: latest
  makeReleaseBuild: false
  lint: false
  runCsTests: true
```
